OBJECTS = main_simple.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc libpacarana:gcc liblsm:gcc

include tools/maker/Makefile
