PACARANA_ROOT ?= $(TOOL_ROOT)/pacarana
PACARANA_LIB = $(PACARANA_ROOT)/LLVM/tasks.so

PACARANA_RUNTIME = $(PACARANA_ROOT)/Pacarana

override CFLAGS += -I$(PACARANA_ROOT)/libpacarana/src/include/libpacarana/pacarana.h
