OBJECTS = main.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc libhmc:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc libpacarana:gcc liblsm:gcc \
        libfxdmath:gcc

include tools/maker/Makefile
