OBJECTS = main.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc libmat:gcc libmspuartlink:gcc \
        libapds:gcc libfxl:gcc libcapybara:gcc libmspware:gcc libmsp:gcc

include tools/maker/Makefile
