LIB = libpacarana

OBJECTS = pacarana.o\

DEPS += libalpaca libmsp

override SRC_ROOT = ../../src

override CFLAGS += \
	-I$(SRC_ROOT)/include/$(LIB)/ \

include $(MAKER_ROOT)/Makefile.$(TOOLCHAIN)


