OBJECTS = main.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:clang libfixed:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc libpacarana:gcc

include tools/maker/Makefile
