OBJECTS = main.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc libmat:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc

include tools/maker/Makefile
