OBJECTS = main.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libfxl:gcc libmsp:gcc

include tools/maker/Makefile
