OBJECTS = main_crunch_current_profile.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc liblsm:gcc \
        libfxdmath:gcc liblps:gcc

include tools/maker/Makefile
