OBJECTS = main_rsa.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc \
        libradio:clang libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc libpacarana:gcc liblsm:clang \
        libfxdmath:gcc

include tools/maker/Makefile
