OBJECTS = main_d7z_paca.o
EXEC = tutorial

DEPS = libmspbuiltins:gcc libio:gcc libfixed:gcc \
        libradio:gcc libcapybara:gcc libmspuartlink:gcc libmspware:gcc \
        libapds:gcc libfxl:gcc libmsp:gcc libpacarana:gcc liblsm:gcc \
        libhmc:gcc liblps:gcc

include tools/maker/Makefile
